//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.BodyBasics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.25,-0.51,2.14")]
        public global::System.Windows.Media.Media3D.Vector3D hot1Vec {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["hot1Vec"]));
            }
            set {
                this["hot1Vec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,10,10")]
        public global::System.Windows.Media.Media3D.Vector3D hot2Vec {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["hot2Vec"]));
            }
            set {
                this["hot2Vec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0")]
        public global::System.Windows.Media.Media3D.Vector3D hot3Vec {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["hot3Vec"]));
            }
            set {
                this["hot3Vec"] = value;
            }
        }
    }
}
